import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./contexts/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          obsidian: "#070807",
          espresso: "#1F1C18",
          crimson: "#DD423F",
          gold: "#E1C499",
          platinum: "#E2E8F0",
          emerald: "#10B981",
        },
        status: {
          success: "#059669",
          error: "#DC2626",
        },
        "surface-variant": "#333535",
        "surface-dim": "#121414",
        "inverse-on-surface": "#2f3131",
        "surface-tint": "#e9c349",
        "primary-fixed-dim": "#e9c349",
        "error": "#ffb4ab",
        "on-tertiary-container": "#8f001b",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e2e2e2",
        "surface-bright": "#38393a",
        "secondary-fixed-dim": "#c8c6c5",
        "background": "#121414",
        "primary": "#f2ca50",
        "on-primary-fixed-variant": "#574500",
        "on-primary": "#3c2f00",
        "on-tertiary-fixed": "#410007",
        "on-surface-variant": "#d0c5af",
        "surface-container-lowest": "#0c0f0f",
        "secondary": "#c8c6c5",
        "on-secondary": "#313030",
        "on-primary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#92001c",
        "outline-variant": "#4d4635",
        "on-primary-container": "#554300",
        "tertiary": "#ffbebc",
        "error-container": "#93000a",
        "secondary-container": "#474746",
        "surface-container-high": "#282a2b",
        "on-secondary-fixed": "#1c1b1b",
        "surface": "#121414",
        "on-secondary-fixed-variant": "#474746",
        "on-tertiary": "#680011",
        "on-surface": "#e2e2e2",
        "on-error": "#690005",
        "tertiary-fixed": "#ffdad8",
        "surface-container-low": "#1a1c1c",
        "primary-fixed": "#ffe088",
        "primary-container": "#d4af37",
        "surface-container": "#1e2020",
        "outline": "#99907c",
        "on-secondary-container": "#b7b5b4",
        "surface-container-highest": "#333535",
        "tertiary-fixed-dim": "#ffb3b1",
        "tertiary-container": "#ff9594",
        "on-background": "#e2e2e2",
        "inverse-primary": "#735c00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        display: [
          "var(--font-playfair)",
          "ui-serif",
          "system-ui",
          "serif",
        ],
        quote: ["var(--font-merienda)", "cursive"],
        serif: ["Cormorant Garamond", "serif"],
        "body-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "label-sm": ["Manrope"],
        "headline-lg-mobile": ["Libre Caslon Text"],
        "label-lg": ["Manrope"],
        "headline-md": ["Libre Caslon Text"],
        "display-lg": ["Libre Caslon Text"],
        "headline-lg": ["Libre Caslon Text"]
      },
      fontWeight: {
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        extrabold: "800",
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1.00rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1.00rem", { lineHeight: "1.50rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.875rem" }],
        "2xl": ["1.50rem", { lineHeight: "2.00rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.75rem" }],
        "5xl": ["3.00rem", { lineHeight: "3.50rem" }],
        "6xl": ["3.75rem", { lineHeight: "4.25rem" }],
        "7xl": ["4.50rem", { lineHeight: "5.00rem" }],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "fontWeight": "400"}]
      },
    },
  },
  plugins: [],
};

export default config;
